behaviors:
  Sudoku:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 5.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 0.1
      gail:
        strength: 0.9
        gamma: 0.8
        demo_path: D:\Unity Projects\Sudoku\Demos\sudokuEasy.demo
    behavioral_cloning:
      strength: 0.9
      gamma: 0.8
      demo_path: D:\Unity Projects\Sudoku\Demos\sudokuEasy.demo
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 20000
    
environment_parameters:
  min_known_numbers:
    curriculum:
      - name: Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Sudoku
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 80
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Sudoku
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 79
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Sudoku
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 78
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Sudoku
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 71
      - name: Lesson4
        value: 61